description: This repository contains the codes, support links and other relevant materials for every class under Computer Club, MNNIT Allahabad.
disqus_shortname: computer-club
image: sample_image.png
theme: jekyll-theme-hacker
title: MNNIT Computer Club
url: cc-mnnit.github.io/2018-19-Classes
